//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace InfrastructureBaselineSolution.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RegiztriesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RegiztriesContainer object using the connection string found in the 'RegiztriesContainer' section of the application configuration file.
        /// </summary>
        public RegiztriesContainer() : base("name=RegiztriesContainer", "RegiztriesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RegiztriesContainer object.
        /// </summary>
        public RegiztriesContainer(string connectionString) : base(connectionString, "RegiztriesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RegiztriesContainer object.
        /// </summary>
        public RegiztriesContainer(EntityConnection connection) : base(connection, "RegiztriesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Scrunchy> Scrunchies
        {
            get
            {
                if ((_Scrunchies == null))
                {
                    _Scrunchies = base.CreateObjectSet<Scrunchy>("Scrunchies");
                }
                return _Scrunchies;
            }
        }
        private ObjectSet<Scrunchy> _Scrunchies;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Scrunchies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScrunchies(Scrunchy scrunchy)
        {
            base.AddObject("Scrunchies", scrunchy);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Regiztries", Name="Scrunchy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Scrunchy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Scrunchy object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Scrunchy CreateScrunchy(global::System.Guid id)
        {
            Scrunchy scrunchy = new Scrunchy();
            scrunchy.Id = id;
            return scrunchy;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        #endregion
    
    }

    #endregion
    
}
