//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZenGarden {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZenGarden() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ZenGarden", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Beauty of &lt;acronym title=&quot;Cascading Style Sheets&quot;&gt;CSS&lt;/acronym&gt; Design.
        /// </summary>
        internal static string BeautyOfCss {
            get {
                return ResourceManager.GetString("BeautyOfCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A demonstration of what can be accomplished visually through &lt;acronym title=&quot;Cascading Style Sheets&quot;&gt;
        ///                CSS&lt;/acronym&gt;-based design. Select any style sheet from the list to load it into
        ///                this page..
        /// </summary>
        internal static string QuickSummaryP1 {
            get {
                return ResourceManager.GetString("QuickSummaryP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the sample &lt;a href=&quot;zengarden-sample.html&quot; title=&quot;This page&apos;s source HTML code, not to be modified.&quot;&gt;
        ///                html file&lt;/a&gt; and &lt;a href=&quot;zengarden-sample.css&quot; title=&quot;This page&apos;s sample CSS, the file you may modify.&quot;&gt;
        ///                    css file&lt;/a&gt;.
        /// </summary>
        internal static string QuickSummaryP2 {
            get {
                return ResourceManager.GetString("QuickSummaryP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Baseline Solution css Zen Garden Page.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
